// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tswsugxjztuuvwhoinmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzd3N1Z3hqenR1dXZ3aG9pbm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDc3NjAsImV4cCI6MjA2OTgyMzc2MH0._HzvpzyUHNUCNl5cyZRAmPrUWksLzAeAkZNhGRg6U9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});